### ISSUE TITLE
Make residue_map_ a std::map, not a vector1<std::pair<Size, Size>>

### ISSUE THREAD

**Issue by kalekundert** [kalekundert/kic_in_the_pants#11]
This is probably not worth it in terms of getting something working ASAP, but it's just driving me crazy.

**Comment by everyday847** [comment]
I tend to agree in general, but std::map don't guarantee ordering. Do we
actually want to guarantee ordering of some kind, which the vector1 does
do? Hm... I don't think so, but it's something to keep in mind.

**Comment by everyday847** [comment]
Doing the same for the atom_list vector of pairs. Should be an atom id to
size map.

**Comment by everyday847** [comment]
Er, atom_list to Vector.

**Comment by everyday847** [comment]
I'm actually not sure about this one. It looks like he does use the order
sometimes. This deserves some thought: maybe (probably) the key-sorted
order is guaranteed correct.

**Comment by everyday847** [comment]
Done. Only just now saw that you'd assigned it to yourself because I was just using the emails. Dumb me. Oh well. Also, we should not do this to atom_list. The order is essential, obviously. Perhaps there is a better way, but it isn't that.
